# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
    
defaults:
  run: 
    working-directory: client

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    services:
        postgres:
          image: postgres:13-alpine
          env:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
          ports:
            - 5432:5432
          # needed because the postgres container does not provide a healthcheck
          options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - run: npm ci
    - run: CI='' npm run build --if-present
    - run: npm ci
      working-directory: server
    - run: CI='' npm run build --if-present
      working-directory: server
      
    - name: Checkout source
      uses: actions/checkout@v2
    - run: npm test
    
    - name: Run the tests and generate coverage report
      run: npm test -- --coverage
  
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
