name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
defaults:
  run: 
    working-directory: client

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
       
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: CI='' npm run build --if-present    
    - run: npm test 
      
    - name: Run the tests and generate coverage report
      run: npm test -- --coverage 
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1

